apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: nginx
    repo: oci://registry-1.docker.io/bitnamicharts/nginx
    includeCRDs: true
    valuesFile: values.yaml
    version: 4.10.0
    releaseName: east