apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: nginx
    repo: oci://registry-1.docker.io/bitnamicharts
    includeCRDs: true
    valuesFile: values.yaml
    version: 15.14.0
    releaseName: east

patches:
- target:
    kind: Service
  patch: |-
    - op: replace
      path: /spec/type
      value: ClusterIP